### ISSUE TITLE
Access denied when downloading pre-trained model weights

### ISSUE THREAD

**Issue by ajndkr** [TracelessLe/FaceParsing.PyTorch#1]
Hi @TracelessLe, great work! 

I am trying to download the pretrained weights and I get an "Access Denied" message on GDrive. Is it on purpose?

**Comment by TracelessLe** [comment]
> Hi @TracelessLe, great work!
> 
> I am trying to download the pretrained weights and I get an "Access Denied" message on GDrive. Is it on purpose?

Sorry for that, the previous share is expired for unknown reasons. I have updated it and you can get the model from the same link.

**Comment by ajndkr** [comment]
thanks! it works now.
